#!/bin/bash

. ci/vars
docker login -u ${user} -p ${pass}
#docker login -u $DOCKER_USER -p $DOCKER_PASS
docker tag cryptoplay/alpine cryptoplay/alpine:${TAG}
docker push cryptoplay/alpine:${TAG}
docker push cryptoplay/alpine:latest
docker logout

curl -X POST 'https://hooks.microbadger.com/images/cryptoplay/alpine/HTlsERf3kLY4CZ-tMPP1Hywe2Ns='
